### ISSUE TITLE
Cookbook is supposed to be a string, it's a symbol

### ISSUE THREAD

**Issue by jrosen** [jsirex/simple-logstash-cookbook#1]
# 

```
       Error executing action `create` on resource 'logstash_output[base]'
       ================================================================================

       Chef::Exceptions::ValidationFailed
       ----------------------------------
       Option cookbook must be a kind of [String]!  You passed :company.

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_config.rb:42:in `conf_file'
       /tmp/kitchen/cookbooks/simple-logstash/libraries/provider_logstash_config.rb:15:in `action_create'

   Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cookbooks/rjmetrics/recipes/default.rb

        16: logstash_output 'base'
        17: logstash_input 'base'

       Compiled Resource:
       ------------------
```

**Comment by jsirex** [comment]
Hello, @jrosen.

It is hard to me to understand why this fails. Could you please provide me the following:
1. Chef version used
2. Recipe where it declared
3. Compiled Resource

conf_file is actually Chef::Resource::Template, wrapped in my HWRP.

**Comment by jsirex** [comment]
UPD: Looks like I'm detecting cookbook name incorrectly. Will fix it soon.

**Comment by jrosen** [comment]
Thanks! It is detecting the name, but the value of cookbook_name is
apparently a symbol and not a string.

**Comment by jsirex** [comment]
Try cookbook version 0.2.2.

I'll close this bug if you confirm fix.
